security:
  password_hashers:
    App\Entity\User:
      algorithm: bcrypt
    Symfony\Component\Security\Core\User\User:
      algorithm: plaintext
    Symfony\Component\Security\Core\User\InMemoryUser:
      algorithm: plaintext


  role_hierarchy:
    ROLE_MECHANIC: [
      ROLE_VEHICLE_VIEW,
      ROLE_CONTRACTVEHICLE_VIEW,
      ROLE_DRIVER_VIEW,
      ROLE_TRAILER_VIEW,

      #vehicle calendar
      ROLE_TT_VEHICLE_CALENDAR_VIEW,
      ROLE_TT_VEHICLE_CALENDAR_CREATE,
      ROLE_TT_VEHICLE_CALENDAR_EDIT,
      ROLE_TT_VEHICLE_CALENDAR_DELETE,
      ROLE_TT_VEHICLE_CALENDAR_BLOCK,
      ROLE_TT_VEHICLE_CALENDAR_CLOSE,

      #driver calendar
      ROLE_TT_DRIVER_CALENDAR_VIEW,
      ROLE_TT_DRIVER_CALENDAR_CREATE,
      ROLE_TT_DRIVER_CALENDAR_EDIT,
      ROLE_TT_DRIVER_CALENDAR_DELETE,
      ROLE_TT_DRIVER_CALENDAR_BLOCK,
      ROLE_TT_DRIVER_CALENDAR_CLOSE,

      #discharges
      ROLE_TT_DISCHARGE_VIEW,
      ROLE_TT_VEHICLE_REQUEST_DISCHARGE_CREATE,
      ROLE_TT_DISCHARGE_EDIT,
      ROLE_TT_DISCHARGE_DELETE,
      ROLE_TT_DISCHARGE_APPROVE,

      # additional release
      ROLE_TT_VEHICLE_RELEASE_VIEW,
      ROLE_TT_VEHICLE_RELEASE_CREATE,

      # requests
      ROLE_TT_TRANSPORTATION_REQUEST_VIEW,
      ROLE_TT_TRANSPORTATION_REQUEST_CREATE,
      ROLE_TT_TRANSPORTATION_REQUEST_EDIT,
      ROLE_TT_TRANSPORTATION_REQUEST_DELETE,
      ROLE_TT_TRANSPORTATION_REQUEST_APPLICATIONS,
      ROLE_TT_TRANSPORTATION_REQUEST_APPROVE,
      ROLE_TT_TRANSPORTATION_REQUEST_REJECT,
      ROLE_TT_TRANSPORTATION_REQUEST_CANCEL,

      # applications
      ROLE_TT_TRANSPORTATION_APPLICATION_VIEW,
      ROLE_TT_TRANSPORTATION_APPLICATION_CANCEL,

      # inspector events
      ROLE_TT_INSPECTOR_EVENTS_VIEW,

    ]
    ROLE_DISPATCHER: [
      ROLE_VEHICLE_VIEW,
      ROLE_CONTRACTVEHICLE_VIEW,
      ROLE_DRIVER_VIEW,
      ROLE_TRAILER_VIEW,

      #vehicle calendar
      ROLE_TT_VEHICLE_CALENDAR_VIEW,
      ROLE_TT_VEHICLE_CALENDAR_CREATE,
      ROLE_TT_VEHICLE_CALENDAR_EDIT,
      ROLE_TT_VEHICLE_CALENDAR_DELETE,
      ROLE_TT_VEHICLE_CALENDAR_BLOCK,
      ROLE_TT_VEHICLE_CALENDAR_CLOSE,

      #driver calendar
      ROLE_TT_DRIVER_CALENDAR_VIEW,
      ROLE_TT_DRIVER_CALENDAR_CREATE,
      ROLE_TT_DRIVER_CALENDAR_EDIT,
      ROLE_TT_DRIVER_CALENDAR_DELETE,
      ROLE_TT_DRIVER_CALENDAR_BLOCK,
      ROLE_TT_DRIVER_CALENDAR_CLOSE,

      #discharges
      ROLE_TT_DISCHARGE_VIEW,

      # additional release
      ROLE_TT_VEHICLE_RELEASE_VIEW,
      ROLE_TT_VEHICLE_RELEASE_CREATE,

      # requests
      ROLE_TT_TRANSPORTATION_REQUEST_VIEW,
      ROLE_TT_TRANSPORTATION_REQUEST_CREATE,
      ROLE_TT_TRANSPORTATION_REQUEST_EDIT,
      ROLE_TT_TRANSPORTATION_REQUEST_APPROVE,
      ROLE_TT_TRANSPORTATION_REQUEST_REJECT,
      ROLE_TT_TRANSPORTATION_REQUEST_APPLICATIONS,
      ROLE_TT_TRANSPORTATION_REQUEST_CANCEL,

      # applications
      ROLE_TT_TRANSPORTATION_APPLICATION_VIEW,
      ROLE_TT_TRANSPORTATION_APPLICATION_CANCEL,

      # pairs
      ROLE_TT_VEHICLE_TRAIN_DRIVER_PAIR_VIEW,
      ROLE_TT_VEHICLE_TRAIN_DRIVER_PAIR_EDIT,
      ROLE_TT_VEHICLE_TRAIN_DRIVER_PAIR_DELETE,

      # inspector events
      ROLE_TT_INSPECTOR_EVENTS_VIEW,
      ROLE_TT_INSPECTOR_EVENTS_CREATE,
      ROLE_TT_INSPECTOR_EVENTS_EDIT,
      ROLE_TT_INSPECTOR_EVENTS_DELETE,

    ]
    ROLE_DIRECTION_DISPATCHER: [
      ROLE_VEHICLE_VIEW,
      ROLE_CONTRACTVEHICLE_VIEW,
      ROLE_DRIVER_VIEW,
      ROLE_TRAILER_VIEW,

      #vehicle calendar
      ROLE_TT_VEHICLE_CALENDAR_VIEW,

      #driver calendar
      ROLE_TT_DRIVER_CALENDAR_VIEW,

      # requests
      ROLE_TT_TRANSPORTATION_REQUEST_VIEW,
      ROLE_TT_TRANSPORTATION_REQUEST_CREATE,
      ROLE_TT_TRANSPORTATION_REQUEST_EDIT,
      ROLE_TT_TRANSPORTATION_REQUEST_APPROVE,
      ROLE_TT_TRANSPORTATION_REQUEST_REJECT,
      ROLE_TT_TRANSPORTATION_REQUEST_APPLICATIONS,
      ROLE_TT_TRANSPORTATION_REQUEST_CANCEL,

      # applications
      ROLE_TT_TRANSPORTATION_APPLICATION_VIEW,
      ROLE_TT_TRANSPORTATION_APPLICATION_CANCEL,

      # pairs
      ROLE_TT_VEHICLE_TRAIN_DRIVER_PAIR_VIEW,
      ROLE_TT_VEHICLE_TRAIN_DRIVER_PAIR_EDIT,
      ROLE_TT_VEHICLE_TRAIN_DRIVER_PAIR_DELETE,

      # inspector events
      ROLE_TT_INSPECTOR_EVENTS_VIEW,
      ROLE_TT_INSPECTOR_EVENTS_CREATE,
      ROLE_TT_INSPECTOR_EVENTS_EDIT,
      ROLE_TT_INSPECTOR_EVENTS_DELETE,
    ]
    SENIOR_DISPATCHER: [
      ROLE_VEHICLE_VIEW,
      ROLE_CONTRACTVEHICLE_VIEW,
      ROLE_DRIVER_VIEW,
      ROLE_TRAILER_VIEW,

      # vehicle request
      ROLE_TT_VEHICLE_REQUEST_VIEW,
      ROLE_TT_VEHICLE_REQUEST_APPROVE,
      ROLE_TT_VEHICLE_REQUEST_EDIT,
      ROLE_TT_VEHICLE_REQUEST_CANCEL,
      ROLE_TT_VEHICLE_REQUEST_EXPORT,

      # vehicle request correction
      ROLE_TT_VEHICLE_REQUEST_CORRECTION_VIEW,

      # vehicle request summary
      ROLE_TT_VEHICLE_REQUEST_SUMMARY_VIEW,

      #discharges
      ROLE_TT_DISCHARGE_VIEW,
      ROLE_TT_VEHICLE_REQUEST_DISCHARGE_CREATE,
      ROLE_TT_DISCHARGE_EDIT,
      ROLE_TT_DISCHARGE_DELETE,
      ROLE_TT_DISCHARGE_APPROVE,

      # additional release
      ROLE_TT_VEHICLE_RELEASE_VIEW,
      ROLE_TT_VEHICLE_RELEASE_CREATE,

      # requests
      ROLE_TT_TRANSPORTATION_REQUEST_VIEW,
      ROLE_TT_TRANSPORTATION_REQUEST_CREATE,
      ROLE_TT_TRANSPORTATION_REQUEST_EDIT,
      ROLE_TT_TRANSPORTATION_REQUEST_APPROVE,
      ROLE_TT_TRANSPORTATION_REQUEST_REJECT,
      ROLE_TT_TRANSPORTATION_REQUEST_APPLICATIONS,
      ROLE_TT_TRANSPORTATION_REQUEST_CANCEL,

      # applications
      ROLE_TT_TRANSPORTATION_APPLICATION_VIEW,
      ROLE_TT_TRANSPORTATION_APPLICATION_CANCEL,

      # pairs
      ROLE_TT_VEHICLE_TRAIN_DRIVER_PAIR_VIEW,
      ROLE_TT_VEHICLE_TRAIN_DRIVER_PAIR_EDIT,
      ROLE_TT_VEHICLE_TRAIN_DRIVER_PAIR_DELETE,

      # inspector events
      ROLE_TT_INSPECTOR_EVENTS_VIEW,
      ROLE_TT_INSPECTOR_EVENTS_CREATE,
      ROLE_TT_INSPECTOR_EVENTS_EDIT,
      ROLE_TT_INSPECTOR_EVENTS_DELETE,


    ]
    ROLE_CONTRACTOR_ENGINEER: [
      ROLE_VEHICLE_VIEW,
      ROLE_CONTRACTVEHICLE_VIEW,
      ROLE_DRIVER_VIEW,
      ROLE_TRAILER_VIEW,

      #vehicle calendar
      ROLE_TT_VEHICLE_CALENDAR_VIEW,
      ROLE_TT_VEHICLE_CALENDAR_CREATE,
      ROLE_TT_VEHICLE_CALENDAR_EDIT,
      ROLE_TT_VEHICLE_CALENDAR_DELETE,
      ROLE_TT_VEHICLE_CALENDAR_BLOCK,
      ROLE_TT_VEHICLE_CALENDAR_CLOSE,

      #driver calendar
      ROLE_TT_DRIVER_CALENDAR_VIEW,
      ROLE_TT_DRIVER_CALENDAR_CREATE,
      ROLE_TT_DRIVER_CALENDAR_EDIT,
      ROLE_TT_DRIVER_CALENDAR_DELETE,
      ROLE_TT_DRIVER_CALENDAR_BLOCK,
      ROLE_TT_DRIVER_CALENDAR_CLOSE,

      #discharges
      ROLE_TT_DISCHARGE_VIEW,

      # additional release
      ROLE_TT_VEHICLE_RELEASE_VIEW,
      ROLE_TT_VEHICLE_RELEASE_CREATE,
    ]
    ROLE_INSPECTOR: [
      ROLE_VEHICLE_VIEW,
      ROLE_CONTRACTVEHICLE_VIEW,
      ROLE_DRIVER_VIEW,
      ROLE_TRAILER_VIEW,

      #discharges
      ROLE_TT_DISCHARGE_VIEW,

      # pairs
      ROLE_TT_VEHICLE_TRAIN_DRIVER_PAIR_VIEW,

      # inspector events
      ROLE_TT_INSPECTOR_EVENTS_VIEW,
      ROLE_TT_INSPECTOR_EVENTS_CREATE,
    ]
    ROLE_CUSTOMER: [
      ROLE_VEHICLE_VIEW,
      ROLE_CONTRACTVEHICLE_VIEW,
      ROLE_DRIVER_VIEW,
      ROLE_TRAILER_VIEW,

      # requests
      ROLE_TT_TRANSPORTATION_REQUEST_VIEW,
      ROLE_TT_TRANSPORTATION_REQUEST_CREATE,
      ROLE_TT_TRANSPORTATION_REQUEST_EDIT,
      ROLE_TT_TRANSPORTATION_REQUEST_DELETE,
      ROLE_TT_TRANSPORTATION_REQUEST_APPLICATIONS,
      ROLE_TT_TRANSPORTATION_REQUEST_APPROVE,
      ROLE_TT_TRANSPORTATION_REQUEST_REJECT,
      ROLE_TT_TRANSPORTATION_REQUEST_CANCEL,

      # applications
      ROLE_TT_TRANSPORTATION_APPLICATION_VIEW,
      ROLE_TT_TRANSPORTATION_APPLICATION_CANCEL,
    ]
    ROLE_MOBILE: [ ROLE_USER ]
    ROLE_SUPPORT: [ ROLE_IMPERSONATE, ROLE_USER_VIEW ]
    ROLE_ADMIN: [
      ROLE_MECHANIC,
      ROLE_DISPATCHER,
      ROLE_DIRECTION_DISPATCHER,
      SENIOR_DISPATCHER,
      ROLE_CONTRACTOR_ENGINEER,
      ROLE_INSPECTOR,
      ROLE_SUPPORT,
    ]

  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  providers:
    chain_provider:
      chain:
        providers: [ in_memory, app_user_provider ]
    in_memory:
      memory:
        users:
          admin: { password: 'admin', roles: [ ROLE_USER, ROLE_ADMIN ] }
    app_user_provider:
      entity:
        class: 'App\Entity\User'
        property: 'loginLc'

  firewalls:
    dev:
      pattern: ^/api/
      security: false
    public:
      pattern: ^/public/

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#firewalls-authentication

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  access_control:
    # { path: ^/, roles: ROLE_USER }
    # - { path: ^/profile, roles: ROLE_USER }
    - { path: ^/api, roles: PUBLIC_ACCESS }

